language: csharp

sudo: false

mono: none

dotnet: 2.1.504

before_script:
  - dotnet restore TravisTestProj_Factorial/TravisTestProj_Factorial.sln

script:
  - dotnet build TravisTestProj_Factorial/TravisTestProj_Factorial.sln --configuration Release
  - dotnet test --configuration Release --no-build TravisTestProj_Factorial/Unit_Tests/Unit_Tests.csproj

after_scipt:
  - bash <(curl -s https://codecov.io/bash)