language: csharp

solution: TravisTestProj_Factorial.sln

dotnet: 2.1.504
sudo: false

install:
  - dotnet restore

script:
  - dotnet build --configuration Release

after_scipt:
  - bash <(curl -s https://codecov.io/bash)